generators:
  # TypeScript/JavaScript SDK
  typescript-axios:
    outputDir: ./sdks/typescript
    packageName: "@griddy/nfl-api"
    packageVersion: "1.0.0"
    npmName: "@griddy/nfl-api"
    withInterfaces: true
    withoutRuntimeChecks: false
    generateAliasAsModel: true

  # Python SDK
  python:
    outputDir: ./sdks/python
    packageName: "griddy_nfl_api"
    packageVersion: "1.0.0"
    projectName: "griddy-nfl-api"
    packageUrl: "https://github.com/griddy/nfl-api-python"

  # Java SDK
  java:
    outputDir: ./sdks/java
    groupId: "com.griddy"
    artifactId: "nfl-api"
    artifactVersion: "1.0.0"
    apiPackage: "com.griddy.nfl.api"
    modelPackage: "com.griddy.nfl.model"
    invokerPackage: "com.griddy.nfl.client"

  # Go SDK
  go:
    outputDir: ./sdks/go
    packageName: "nflapi"
    packageVersion: "1.0.0"
    moduleName: "github.com/griddy/nfl-api-go"

  # C# SDK
  csharp:
    outputDir: ./sdks/csharp
    packageName: "Griddy.NFL.Api"
    packageVersion: "1.0.0"
    clientPackage: "Griddy.NFL.Api.Client"
    packageCompany: "Griddy"
    packageAuthors: "Griddy Team"
    packageDescription: "NFL API SDK for .NET"

# Common configuration
globalProperties:
  models: ""
  apis: ""
  supportingFiles: ""
  modelTests: false
  apiTests: false
  modelDocs: false
  apiDocs: false