name: Generate and Publish SDKs with Speakeasy

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'openapi/nfl-com-api.yaml'
      - '.speakeasy/**'
  workflow_dispatch:

jobs:
  generate-python-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Setup Speakeasy
        uses: speakeasy-api/sdk-generation-action@v15
        with:
          speakeasy_version: latest
          mode: pr
          languages: python
          openapi_doc_location: ./openapi/nfl-com-api.yaml
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}

      - name: Generate Python SDK
        run: |
          speakeasy generate sdk \
            --schema ./openapi/nfl-com-api.yaml \
            --lang python \
            --out ./python-sdk \
            -y

      - name: Setup Python and uv
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Configure Python SDK for uv
        working-directory: python-sdk
        run: |
          # Add pyproject.toml build system configuration for uv
          if [ ! -f pyproject.toml ]; then
            cat > pyproject.toml << 'EOF'
          [build-system]
          requires = ["hatchling"]
          build-backend = "hatchling.build"

          [project]
          name = "griddy-nfl"
          dynamic = ["version"]
          description = "Python SDK for NFL API"
          readme = "README.md"
          requires-python = ">=3.13"
          dependencies = []

          [tool.hatch.version]
          path = "src/griddy_nfl/__init__.py"
          EOF
          fi

      - name: Checkout Python SDK repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/griddy-nfl-python
          token: ${{ secrets.SDK_DEPLOY_TOKEN }}
          path: python-sdk-repo

      - name: Copy generated SDK to repository
        run: |
          # Preserve custom authorization wrapper if it exists
          if [ -f python-sdk-repo/griddy_nfl/auth.py ]; then
            cp python-sdk-repo/griddy_nfl/auth.py /tmp/auth.py
          fi

          rm -rf python-sdk-repo/*
          cp -r python-sdk/* python-sdk-repo/

          # Restore custom authorization wrapper
          if [ -f /tmp/auth.py ]; then
            cp /tmp/auth.py python-sdk-repo/griddy_nfl/auth.py
          fi

      - name: Commit and push Python SDK
        working-directory: python-sdk-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update SDK from OpenAPI spec [skip ci]" && git push)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get CodeArtifact authorization token
        id: codeartifact-token
        run: |
          TOKEN=$(aws codeartifact get-authorization-token \
            --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
            --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} \
            --query authorizationToken \
            --output text)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

          REPO_URL=$(aws codeartifact get-repository-endpoint \
            --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
            --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} \
            --repository ${{ secrets.CODEARTIFACT_REPO }} \
            --format pypi \
            --query repositoryEndpoint \
            --output text)
          echo "repo_url=$REPO_URL" >> $GITHUB_OUTPUT

      - name: Build Python package
        working-directory: python-sdk-repo
        run: |
          uv build

      - name: Publish to CodeArtifact
        working-directory: python-sdk-repo
        env:
          CODEARTIFACT_TOKEN: ${{ steps.codeartifact-token.outputs.token }}
          REPO_URL: ${{ steps.codeartifact-token.outputs.repo_url }}
        run: |
          # Configure uv to use CodeArtifact
          uv publish \
            --publish-url "${REPO_URL}simple/" \
            --token "aws:${CODEARTIFACT_TOKEN}" \
            --username aws

  generate-typescript-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Speakeasy
        uses: speakeasy-api/sdk-generation-action@v15
        with:
          speakeasy_version: latest
          mode: pr
          languages: typescript
          openapi_doc_location: ./openapi/nfl-com-api.yaml
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}

      - name: Generate TypeScript SDK
        run: |
          speakeasy generate sdk \
            --schema ./openapi/nfl-com-api.yaml \
            --lang typescript \
            --out ./typescript-sdk \
            -y

      - name: Checkout TypeScript SDK repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/griddy-nfl-typescript
          token: ${{ secrets.SDK_DEPLOY_TOKEN }}
          path: typescript-sdk-repo

      - name: Copy generated SDK to repository
        run: |
          # Preserve custom authorization wrapper if it exists
          if [ -f typescript-sdk-repo/src/auth.ts ]; then
            cp typescript-sdk-repo/src/auth.ts /tmp/auth.ts
          fi

          rm -rf typescript-sdk-repo/*
          cp -r typescript-sdk/* typescript-sdk-repo/

          # Restore custom authorization wrapper
          if [ -f /tmp/auth.ts ]; then
            cp /tmp/auth.ts typescript-sdk-repo/src/auth.ts
          fi

      - name: Commit and push TypeScript SDK
        working-directory: typescript-sdk-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update SDK from OpenAPI spec [skip ci]" && git push)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get CodeArtifact authorization token and configure npm
        working-directory: typescript-sdk-repo
        run: |
          # Get authorization token
          TOKEN=$(aws codeartifact get-authorization-token \
            --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
            --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} \
            --query authorizationToken \
            --output text)

          # Get repository endpoint
          REPO_URL=$(aws codeartifact get-repository-endpoint \
            --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
            --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} \
            --repository ${{ secrets.CODEARTIFACT_REPO }} \
            --format npm \
            --query repositoryEndpoint \
            --output text)

          # Configure npm to use CodeArtifact
          npm config set registry "${REPO_URL}"
          npm config set //${REPO_URL#https://}:_authToken="${TOKEN}"
          npm config set //${REPO_URL#https://}:always-auth=true

      - name: Build and publish TypeScript SDK
        working-directory: typescript-sdk-repo
        run: |
          npm install
          npm run build
          npm publish
