name: Lint API Spec

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: 

jobs:
  lint-openapi:
    name: Lint using Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: '*.oas.{json,yml,yaml}'
